apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-k8s-deployment
spec:
  selector:
    matchLabels:
      app: healthcare-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: healthcare-k8s
    spec:
      containers:
        - name: healthcare-k8s
          image: pranavkul07/staragileprojecthealthcare:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090

---

apiVersion: v1
kind: Service
metadata:
  name: healthcare-k8ssvc
spec:
  selector:
    app: healthcare-k8s
  type: NodePort
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30909  # 👈 Add this line to expose the app on this port
